# A Windows based image with Docker engine (EE) installed, that registers itself as a Jenkins Agent.

# TODO: use microsoft.mcr/windowsservercore
FROM jenkins/jenkins:latest

# install the Jenkins Swarm plugin client
# https://wiki.jenkins.io/display/JENKINS/Swarm+Plugin

