# version: '3.9'

name: jenkins
services:
  controller:
    # container_name: jenkins-controller
    hostname: controller
    # image: jenkins/jenkins:lts
    image: jenkins-controller
    build: controller
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - controller_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./controller/jobs:/var/jenkins_home/jobs
      - ./controller/dsl:/usr/share/jenkins/dsl
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins/casc/jenkins.yaml
    configs:
      - source: controller_config
        target: /var/jenkins/casc/jenkins.yaml
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs/wildcard.moria.local.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
      - ./certs/wildcard.moria.local.key:/etc/ssl/private/nginx-selfsigned.key:ro
  test:
    image: nginx:stable

volumes:
  controller_home:

configs:
  controller_config:
    file: controller/jenkins.yaml
