# version: '3.9'

name: jenkins
services:
  controller:
    # container_name: jenkins-controller
    # hostname: jenkins-controller
    # image: jenkins/jenkins:lts
    image: jenkins-controller
    build: controller
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - controller_home:/var/jenkins_home
      # - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ./controller/jobs:/var/jenkins_home/jobs
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins/casc/jenkins.yaml
    configs:
      - source: controller_config
        target: /var/jenkins/casc/jenkins.yaml

volumes:
  controller_home:

configs:
  controller_config:
    file: controller/jenkins.yaml
