# version: '3.9'

name: jenkins
services:
  controller:
    hostname: controller
    image: jenkins-controller
    build: controller
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - controller_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - ./controller/jobs:/var/jenkins_home/jobs
      - ./controller/dsl:/usr/share/jenkins/dsl:ro
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins/casc/jenkins.yaml
    configs:
      - source: controller_config
        target: /var/jenkins/casc/jenkins.yaml
    secrets:
      - JENKINS_ADMINISTRATOR_USERNAME
      - JENKINS_ADMINISTRATOR_PASSWORD
      - JENKINS_SWARM_USER
      - JENKINS_SWARM_PASSWORD
  nginx: # reverse proxy
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs/wildcard.moria.local.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
      - ./certs/wildcard.moria.local.key:/etc/ssl/private/nginx-selfsigned.key:ro
  test: # 'dummy' website to test the nginx configuration for multiple websites
    image: nginx:stable

volumes:
  controller_home:

configs:
  controller_config:
    file: controller/jenkins.yaml

secrets:
  JENKINS_ADMINISTRATOR_USERNAME:
    file: ./secrets/admin-user
  JENKINS_ADMINISTRATOR_PASSWORD:
    file: ./secrets/admin-password
  JENKINS_SWARM_USER:
    file: ./secrets/swarm-user
  JENKINS_SWARM_PASSWORD:
    file: ./secrets/swarm-password
