version: '3.7'

services:
  jenkins-master:
    container_name: jenkins
    image: jenkins-master
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins-master:/var/jenkins_home
    build:
      context: .\jenkins-master
      dockerfile: Dockerfile
      args:
        buildno: 1
        JENKINS_URL: http://jenkins:8080

  jenkins-agent:
    container_name: jenkins-agent
    image: jenkins-agent
    restart: always
    environment:
      - 'JENKINS_URL=http://jenkins:8080'
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins-master
    build:
      context: .\jenkins-agent-docker-host
      dockerfile: Dockerfile
      args:
        buildno: 1
    
volumes:
  jenkins-master:

    