jenkins:
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  systemMessage: |
    # Jenkins configured using Jenkins Configuration as Code
    See <https://jenkins.moria.local/manage/configuration-as-code/>
  markupFormatter: "markdownFormatter"
  securityRealm:
    local:
      allowsSignup: true
      enableCaptcha: false

unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
    - simpleBuildDiscarder:
        discarder:
          logRotator:
            daysToKeepStr: "100"
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  pollSCM:
    pollingThreadCount: 10

tool:
  dockerTool:
    installations:
    - name: "docker@latest"
      properties:
      - installSource:
          installers:
          - fromDocker:
              version: "latest"

jobs:
  - file: /usr/share/jenkins/dsl/jenkinsfiles.groovy
