jenkins:
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  systemMessage: |
    # Jenkins configured using Jenkins Configuration as Code
    See <https://jenkins.moria.local/manage/configuration-as-code/>
  markupFormatter: "markdownFormatter"
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "${JENKINS_ADMINISTRATOR_USERNAME:-admin}"
          password: "${JENKINS_ADMINISTRATOR_PASSWORD:-jcasc}"
        - id: "${JENKINS_SWARM_USER}"
          password: "${JENKINS_SWARM_PASSWORD:-swarm}"
  authorizationStrategy:
    globalMatrix:
      permissions:
      - "USER:Agent/Connect:${JENKINS_SWARM_USER}"
      - "USER:Agent/Disconnect:${JENKINS_SWARM_USER}"
      - "USER:Agent/Create:${JENKINS_SWARM_USER}"
      # - "USER:Agent/Delete:anonymous"
      # - "USER:Overall/Read:anonymous"     # needed for anonymously connecting a swarm agent
      - "GROUP:Overall/Administer:authenticated"
      - "USER:Overall/Administer:${JENKINS_ADMINISTRATOR_USERNAME}"

unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
    - simpleBuildDiscarder:
        discarder:
          logRotator:
            daysToKeepStr: "100"
  location:
    adminAddress: "nobody@nowhere"
    url: "${JENKINS_URL_CASC}"

tool:
  dockerTool:
    installations:
    - name: "docker@latest"
      properties:
      - installSource:
          installers:
          - fromDocker:
              version: "latest"

jobs:
  - file: /usr/share/jenkins/dsl/jenkinsfiles.groovy
