jenkins:
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  systemMessage: |
    # Jenkins configured using Jenkins Configuration as Code
    See <https://jenkins.test.local/manage/configuration-as-code/>
  markupFormatter: "markdownFormatter"
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "${JENKINS_ADMINISTRATOR_USERNAME:-admin}"
          password: "${JENKINS_ADMINISTRATOR_PASSWORD:-jcasc}"
        - id: "${JENKINS_SWARM_USER}"
          password: "${JENKINS_SWARM_PASSWORD:-swarm}"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "USER:Agent/Connect:${JENKINS_SWARM_USER}"
        - "USER:Agent/Disconnect:${JENKINS_SWARM_USER}"
        - "USER:Agent/Create:${JENKINS_SWARM_USER}"
        # - "USER:Agent/Delete:anonymous"
        # - "USER:Overall/Read:anonymous"     # needed for anonymously connecting a swarm agent
        - "GROUP:Overall/Administer:authenticated"
        - "USER:Overall/Administer:${JENKINS_ADMINISTRATOR_USERNAME}"
  nodes:
    - permanent:
        labelString: "linux"
        launcher:
          ssh:
            credentialsId: "ssh-agent-key"
            host: "ssh-agent"
            port: 22
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false
        name: "ssh-agent"
        remoteFS: "/home/jenkins/agent"
        retentionStrategy: "always"

security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  queueItemAuthenticator:
    authenticators:
      - global:
          strategy: "triggeringUsersAuthorizationStrategy"

unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
      - simpleBuildDiscarder:
          discarder:
            logRotator:
              daysToKeepStr: "100"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleOnOver
  location:
    adminAddress: "nobody@nowhere"
    url: "${JENKINS_URL_CASC}"

tool:
  dockerTool:
    installations:
      - name: "docker@latest"
        properties:
          - installSource:
              installers:
                - fromDocker:
                    version: "latest"

jobs:
  - file: /usr/share/jenkins/dsl/jenkinsfiles.groovy
  - file: /usr/share/jenkins/dsl/dsl-playground.groovy
  - file: /usr/share/jenkins/dsl/jobsFromGithub.groovy

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: SYSTEM
              id: ssh-agent-key
              username: jenkins # defined in docker image jenkins/ssh-agent:*
              usernameSecret: true
              passphrase: ""
              # description: "ssh key used to connect ssh agents"
              privateKeySource:
                directEntry:
                  privateKey: ${SSH_AGENT_PRIVATE_KEY} # secret defined in compose.yml
          - usernamePassword:
              id: "github-credentials"
              password: "${GITHUB_PAT}"
              scope: GLOBAL
              username: "MarnixKoerselman"
              usernameSecret: true
