jenkins:
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  # port needed for swarm clients
  slaveAgentPort: 50000
  systemMessage: |
    # Jenkins configured using Jenkins Configuration as Code
    See the [Configuration as Code page](/manage/configuration-as-code/).
  markupFormatter: "markdownFormatter"
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "${JENKINS_ADMINISTRATOR_USERNAME:-admin}"
          password: "${JENKINS_ADMINISTRATOR_PASSWORD:-jcasc}"
        - id: "${JENKINS_SWARM_USER}"
          password: "${JENKINS_SWARM_PASSWORD:-swarm}"
  authorizationStrategy:
    globalMatrix:
      entries:
        - group:
            name: "authenticated"
            permissions:
              - "Overall/Administer"
        - user:
            name: "${JENKINS_ADMINISTRATOR_USERNAME:-admin}"
            permissions:
              - "Overall/Administer"
        - user:
            name: "${JENKINS_SWARM_USER}"
            permissions:
              - "Agent/Connect"
              - "Agent/Disconnect"
              - "Agent/Create"
  nodes:
    - permanent:
        labelString: "linux alpine"
        launcher:
          ssh:
            credentialsId: "ssh-agent-key"
            host: "ssh-agent"
            port: 22
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false
        name: "ssh-agent"
        remoteFS: "/home/jenkins/agent"
        retentionStrategy: "always"
    - permanent:
        labelString: "inbound windows ws2022"
        launcher: "inbound"
        name: "ws2022-inbound-agent"
        remoteFS: "c:\\jenkins"
        retentionStrategy: "always"
  numExecutors: 0

security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  queueItemAuthenticator:
    authenticators:
      - global:
          strategy: "triggeringUsersAuthorizationStrategy"

unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
      - simpleBuildDiscarder:
          discarder:
            logRotator:
              daysToKeepStr: "100"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleOnOver
  location:
    adminAddress: "nobody@nowhere"
    url: "${JENKINS_URL_CASC}"

tool:
  git:
    installations:
      - home: "git"
        name: "Default"
        properties:
          - installSource:
              installers:
                - zip:
                    label: "windows && x64"
                    subdir: "cmd\\git.exe"
                    url: "https://github.com/git-for-windows/git/releases/download/v2.52.0.windows.1/MinGit-2.52.0-64-bit.zip"
                - zip:
                    label: "windows && x86"
                    subdir: "cmd\\git.exe"
                    url: "https://github.com/git-for-windows/git/releases/download/v2.52.0.windows.1/MinGit-2.52.0-32-bit.zip"

jobs:
  - file: /usr/share/jenkins/dsl/jenkinsfiles.groovy
  - file: /usr/share/jenkins/dsl/dsl-playground.groovy
  - file: /usr/share/jenkins/dsl/jobsFromGithub.groovy

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: SYSTEM
              id: ssh-agent-key
              username: jenkins # defined in docker image jenkins/ssh-agent:*
              usernameSecret: true
              passphrase: ""
              # description: "ssh key used to connect ssh agents"
              privateKeySource:
                directEntry:
                  privateKey: ${SSH_AGENT_PRIVATE_KEY} # secret defined in docker-compose.yml
          - usernamePassword:
              id: "github-credentials"
              password: "${GITHUB_PAT}"
              scope: GLOBAL
              username: "${GITHUB_SLUG}"
              usernameSecret: true
